### PR TITLE
NEW: Upgrade to PHPUnit 9, drop support for PHP < 7.3

### LINKED ISSUE #8: PHP 8 support
In line 16 of https://github.com/marcj/topsort.php/blob/master/src/CircularDependencyException.php, $nodes has no default value but the first 3 arguments do.

In PHP 8, this creates a warning:
> Required parameter $nodes follows optional parameter $message

### PR DESCRIPTION
**Pull request by sminnee**
This will allow support for PHP 8

Fixes #8

### CODE REVIEW

**Comment by sminnee** [comment]
OK, after a number of failed builds due to not having xdebug on my local environment, this is ready:

 * PHPUnit upgraded to v9, with strict coverage
 * PHP requirement as dictated by Composer >= PHP 7.3
 * Test matrix testing 7.3, 7.4, and nightly with `--ignore-platform-reqs`

If acceptable, this could become part of a 1.2.0 or a 2.0.0

**Comment by marcj** [comment]
Great stuff, thank you very much! I'll pusha new release to packagist once PHP 8 is released. I hope I don't miss it. :P

**Comment by sminnee** [comment]
I'll drop you a line when it does, it's likely to be end of Nov I think.

**Comment by Cheddam** [comment]
@marcj PHP 8 is out 🎉 Would you be able to tag 2.0.0 stable?

**Comment by marcj** [comment]
Thanks for the reminder! Done https://github.com/marcj/topsort.php/releases/tag/2.0.0

**Pull request merged**
